# Generated by Django 3.0.4 on 2020-04-14 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_contact_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionwarehouse',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permissionwarehouse',
            name='warehouse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Warehouse'),
        ),
    ]
