# Generated by Django 3.0.4 on 2020-05-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200414_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='warehouse_images/'),
        ),
    ]
