# Generated by Django 3.0.7 on 2021-01-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_warehouse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='address1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address2',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
