# Generated by Django 3.0.4 on 2020-03-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sell_price',
        ),
        migrations.AddField(
            model_name='varianproduct',
            name='buy_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='varianproduct',
            name='sell_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
