# Generated by Django 3.0.4 on 2020-04-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20200402_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varianproduct',
            name='varian',
        ),
        migrations.AddField(
            model_name='varianproduct',
            name='varian_attribute',
            field=models.CharField(choices=[('WARNA', 'Warna'), ('UKURAN', 'Ukuran'), ('BERAT', 'Berat')], default='UKURAN', max_length=10),
        ),
        migrations.AddField(
            model_name='varianproduct',
            name='varian_value',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Varian',
        ),
    ]
