# Generated by Django 3.0.4 on 2020-04-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200408_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='varianproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='varianproduct',
            name='varian_attribute',
            field=models.CharField(choices=[('UKURAN', 'Ukuran'), ('WARNA', 'Warna'), ('BERAT', 'Berat')], default='UKURAN', max_length=10),
        ),
    ]
