# Generated by Django 3.0.7 on 2021-01-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20200507_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varianproduct',
            name='product_type',
            field=models.CharField(help_text='Bisa input warna, atau tipe khusus', max_length=100),
        ),
        migrations.AlterField(
            model_name='varianproduct',
            name='size',
            field=models.CharField(default='1-3', max_length=20),
        ),
    ]
