# Generated by Django 3.0.7 on 2021-01-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20210103_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianproduct',
            name='seri',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
