# Generated by Django 3.0.4 on 2020-04-15 04:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import invoice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_auto_20200414_1329'),
        ('inventory', '0011_auto_20200414_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(default=invoice.models.increment_invoice_number, editable=False, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DEBT', 'Debt'), ('PAID', 'Paid')], default='DRAFT', max_length=10)),
                ('due', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Contact')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
                ('varian_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.VarianProduct')),
            ],
        ),
    ]
