# Generated by Django 3.0.4 on 2020-04-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due',
            field=models.DateField(blank=True, help_text='Format: mm-dd-yyyy', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, help_text='Format: mm-dd-yyyy', null=True),
        ),
    ]
