# Generated by Django 3.0.4 on 2020-04-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20200425_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
