# Generated by Django 3.0.4 on 2020-04-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
