# Generated by Django 3.0.4 on 2020-04-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20200425_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
