# Generated by Django 3.0.4 on 2020-05-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20200507_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('HUTANG', 'Hutang'), ('LUNAS', 'Lunas')], default='DRAFT', max_length=10),
        ),
    ]
